# Generated by Django 6.0.6 on 2026-08-26 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_teachers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teachers',
        ),
    ]
