# Generated by Django 6.0.6 on 2026-08-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='experience',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
